trigger: none

pool:
  name: linux

stages:
# Stage untuk Code Quality (ESLint, SonarQube)
- stage: CodeQuality
  jobs:
    - job: CodeQualityCheck
      steps:
      # Checkout code dari repository GitHub
      - checkout: self
        persistCredentials: true
        fetchDepth: 1
        clean: true

      # Setup Node.js
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '20.x'

      # Install dependencies
      - script: |
          npm install
        displayName: 'Install Dependencies'

      # Install dependencies
      - script: |
          npm audit
        displayName: 'Install Dependencies'

      # Linting dengan fix
      - script: |
          npm install eslint --save-dev
          npx eslint . --config client/eslint.config.js --fix
        displayName: 'Run ESLint with Fix and Report'
      
      # Publish report
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'eslint-report.json'
          ArtifactName: 'ESLint Report'
        displayName: 'Publish ESLint Report'